---
name: IMAP-BodyStructure
version: 1.01
author:
  - 'Alex Kapranoff, E<lt>kappa@rambler-co.ruE<gt>'
abstract: IMAP4-compatible BODYSTRUCTURE and ENVELOPE parser
license: artistic
build_requires:
  Test::NoWarnings: 0
provides:
  IMAP::BodyStructure:
    file: lib/IMAP/BodyStructure.pm
    version: 1.01
  IMAP::BodyStructure::Envelope:
    file: lib/IMAP/BodyStructure.pm
    version: 1.01
generated_by: Module::Build version 0.2611
